version: "3.7"
services:
  app:
    privileged: true
    build:
      args:
        user: rohit
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: travellist-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - travellist

  db:
      image: mysql:8.0
      privileged: true
      container_name: travellist-db
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: pms
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      volumes:
        - ./mysql:/docker-entrypoint-initdb.d
      ports:
        - 33061:3306
      networks:
        - travellist
  nginx:
    image: nginx:alpine
    container_name: travellist-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - travellist

networks:
  travellist:
    driver: bridge